services:
  vlinderd:
    build: .
    depends_on:
      - nats
      - ollama
    ports:
      - "8080:8080"
    environment:
      - VLINDER_DIR=/config
      - RUST_BACKTRACE=1
    volumes:
      - type: bind
        source: ./
        target: /config
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
    command: ["-js"]
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"